### ISSUE TITLE
ARM アーキテクチャのセルフホステッドランナーを用意する

### ISSUE THREAD

**Issue by TeraTorajiro** [bumblebee-jp/self-hosted-runners#1]
## 内容

GHA を ARMアーキテクチャのセルフホステッドランナーで実行したい。

## 構造

以下のようにリレーして GHA を実行します。
CodeBuild は ECR からコンテナイメージ(`actions/runner`)を取ってきます。

GH Webhook -> API Gateway -> Lambda -> CodeBuild -> `actions/runner`

**Comment by TeraTorajiro** [comment]
## ToDo

- [ ] configure GH Webhook 
- [ ] pass fine-grained PAT to Lambda
- [x] setup CDK
  - [x] ECR
  - [x] API Gateway
  - [x] Lambda
  - [ ] CodeBuild
- [ ] least privilege
- [ ] secure integration to API Gateway
  - [x] limited IP range
  - [ ] verify secret token

**Comment by TeraTorajiro** [comment]
codebuild の buildcommand を修正しました。

`duo_rust` レポジトリで self-hosted runner 上で GHA を実行できました。
ちゃんと ARM向けイメージのビルドができるか等は `duo_rust` のチケットして実施してください。
ここでは、とりあえず起動まで確認しています。

レビューに回します。
